# Docker Compose pour PostgreSQL local
version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: roadpress-db-local
    restart: unless-stopped
    environment:
      POSTGRES_USER: roadpress_dev
      POSTGRES_PASSWORD: roadpress_local_2025
      POSTGRES_DB: roadpress_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U roadpress_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: roadpress_postgres_data
